dist: trusty
sudo: false
language: python

python:
    - "2.7"

addons:
    apt:
        packages:
            - php5-cli

install:
# command to run tests

script:
    - "python base8x.py -v"
    - "{ echo '<?php'; python example_wpskg.py; echo '?>'; } | php -l"
